https://github.com/dotnet/vscode-dotnet-runtime/pull/2648/changes do we really need the changes we should just match the upstream main for the changes to glob/rimraf as we are seeing a lot of added complexity and confusion from the usage of rimraf.   src/test/functional/index.ts:5:23 - error TS7016: Could not find a declaration file for module 'glob'. 'D:/vscode-dotnet-runtime/vscode-dotnet-runtime-extension/node_modules/glob/glob.js' implicitly has an 'any' type.   If the 'glob' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'glob';`  5 import * as glob from 'glob';                         ~~~~~~  src/test/functional/index.ts:21:59 - error TS7006: Parameter 'err' implicitly has an 'any' type.  21     glob('**/functional/**.test.js', { cwd: testsRoot }, (err, files) =>                                                              ~~~  src/test/functional/index.ts:21:64 - error TS7006: Parameter 'files' implicitly has an 'any' type.  21     glob('**/functional/**.test.js', { cwd: testsRoot }, (err, files) =>                                                                   ~~~~~  src/test/functional/index.ts:29:21 - error TS7006: Parameter 'f' implicitly has an 'any' type.  29       files.forEach(f => mocha.addFile(path.resolve(testsRoot, f)));                        ~   Found 4 errors in the same file, starting at: src/test/functional/index.ts:5